// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_I2BR-SaN7WiAqO9LFKp8hQYGwnjB17c',
    appId: '1:198386969413:web:32c131d0585d16459a2c2c',
    messagingSenderId: '198386969413',
    projectId: 'basicapp-9be79',
    authDomain: 'basicapp-9be79.firebaseapp.com',
    storageBucket: 'basicapp-9be79.appspot.com',
    measurementId: 'G-Y7XQLLWPG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTyyF8P_kvXvJrO2ZtqYGLHyRtTpqpxxo',
    appId: '1:198386969413:android:b22f4b81139821029a2c2c',
    messagingSenderId: '198386969413',
    projectId: 'basicapp-9be79',
    storageBucket: 'basicapp-9be79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPGKSixvo_iEmX_mAB_DwfEnbK0oH43jk',
    appId: '1:198386969413:ios:46311683fea6252a9a2c2c',
    messagingSenderId: '198386969413',
    projectId: 'basicapp-9be79',
    storageBucket: 'basicapp-9be79.appspot.com',
    iosBundleId: 'com.example.flutterCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPGKSixvo_iEmX_mAB_DwfEnbK0oH43jk',
    appId: '1:198386969413:ios:46311683fea6252a9a2c2c',
    messagingSenderId: '198386969413',
    projectId: 'basicapp-9be79',
    storageBucket: 'basicapp-9be79.appspot.com',
    iosBundleId: 'com.example.flutterCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_I2BR-SaN7WiAqO9LFKp8hQYGwnjB17c',
    appId: '1:198386969413:web:da959008e570aea59a2c2c',
    messagingSenderId: '198386969413',
    projectId: 'basicapp-9be79',
    authDomain: 'basicapp-9be79.firebaseapp.com',
    storageBucket: 'basicapp-9be79.appspot.com',
    measurementId: 'G-WST32RNBFV',
  );
}
